### ISSUE TITLE
Update SQS tests to consume multiple messages at once

### ISSUE THREAD

**Issue by rfk** [harrison-ai/cobalt-aws#150]
The tests in `sqs.rs` include a [`consume_queue`](https://github.com/harrison-ai/cobalt-aws/blob/8ca6465fc543969a3f0efda51943dff321e6138b/src/sqs.rs#L178) function which pulls all outstanding messages off of a queue into a vector. It currently receives just a single message from the queue at a time, but the underlying [`receive_message` method](https://docs.rs/aws-sdk-sqs/latest/aws_sdk_sqs/client/struct.Client.html#method.receive_message) allows receiving a batch of up to 10. The code should be updated to receive messages in batches instead of one at a time.

(There may be some microscopic performance improvement from doing so, but really, this is a nice small self-contained change just to get familiar with building and testing the crate).

**Comment by thauanz** [comment]
@rfk the `receive_message` method allows setting `max_number_of_messages` to 10. However, the `delete_message` still be one by one. I was thinking to try and replace it with the `delete_message_batch`.

**Comment by rfk** [comment]
That sounds good to me!
